
pub fn get_vars() -> Vec<&'static str>{
    let mut files = Vec::new();

    let main_py = "import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from uis.Ui_MainWindow import Ui_MainWindow


class MainWindow:
    def __init__(self) -> None:

        self.main_win = QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.main_win)

        self.ui.btn_greet.clicked.connect(self.greet_person)

    def show(self) -> None:
        self.main_win.show()

    def greet_person(self) -> None:
        name = self.ui.ln_name.text()
        if not name == '':
            self.ui.lbl_greet.setText(f'Hello, {name}!')
        else:
            self.ui.lbl_greet.setText('Put a name in, silly!')



if __name__ == '__main__':
    app = QApplication(sys.argv)
    main_win = MainWindow()
    main_win.show()
    sys.exit(app.exec_())
";

    let ui_mainwindow_py = "# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unconverted_uis/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(300, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName('gridLayout')
        spacerItem = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName('verticalLayout')
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName('formLayout')
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name.setObjectName('lbl_name')
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_name)
        self.ln_name = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_name.setObjectName('ln_name')
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ln_name)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_greet = QtWidgets.QPushButton(self.centralwidget)
        self.btn_greet.setObjectName('btn_greet')
        self.verticalLayout.addWidget(self.btn_greet)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.lbl_greet = QtWidgets.QLabel(self.centralwidget)
        self.lbl_greet.setText('')
        self.lbl_greet.setObjectName('lbl_greet')
        self.verticalLayout.addWidget(self.lbl_greet)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 2, 2)
        spacerItem4 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'MainWindow'))
        self.lbl_name.setText(_translate('MainWindow', 'Name:'))
        self.btn_greet.setText(_translate('MainWindow', 'Greet'))
";

    let mainwindow_ui = "<?xml version='1.0' encoding='UTF-8'?>
<ui version='4.0'>
 <class>MainWindow</class>
 <widget class='QMainWindow' name='MainWindow'>
  <property name='geometry'>
   <rect>
    <x>0</x>
    <y>0</y>
    <width>300</width>
    <height>250</height>
   </rect>
  </property>
  <property name='windowTitle'>
   <string>MainWindow</string>
  </property>
  <widget class='QWidget' name='centralwidget'>
   <layout class='QGridLayout' name='gridLayout'>
    <item row='0' column='1'>
     <spacer name='verticalSpacer_3'>
      <property name='orientation'>
       <enum>Qt::Vertical</enum>
      </property>
      <property name='sizeHint' stdset='0'>
       <size>
        <width>20</width>
        <height>27</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row='1' column='0'>
     <spacer name='horizontalSpacer'>
      <property name='orientation'>
       <enum>Qt::Horizontal</enum>
      </property>
      <property name='sizeHint' stdset='0'>
       <size>
        <width>42</width>
        <height>20</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row='1' column='1' rowspan='2' colspan='2'>
     <layout class='QVBoxLayout' name='verticalLayout'>
      <item>
       <layout class='QFormLayout' name='formLayout'>
        <item row='0' column='0'>
         <widget class='QLabel' name='lbl_name'>
          <property name='text'>
           <string>Name:</string>
          </property>
         </widget>
        </item>
        <item row='0' column='1'>
         <widget class='QLineEdit' name='ln_name'/>
        </item>
       </layout>
      </item>
      <item>
       <spacer name='verticalSpacer_2'>
        <property name='orientation'>
         <enum>Qt::Vertical</enum>
        </property>
        <property name='sizeHint' stdset='0'>
         <size>
          <width>20</width>
          <height>40</height>
         </size>
        </property>
       </spacer>
      </item>
      <item>
       <widget class='QPushButton' name='btn_greet'>
        <property name='text'>
         <string>Greet</string>
        </property>
       </widget>
      </item>
      <item>
       <spacer name='verticalSpacer'>
        <property name='orientation'>
         <enum>Qt::Vertical</enum>
        </property>
        <property name='sizeHint' stdset='0'>
         <size>
          <width>20</width>
          <height>40</height>
         </size>
        </property>
       </spacer>
      </item>
      <item>
       <widget class='QLabel' name='lbl_greet'>
        <property name='text'>
         <string/>
        </property>
       </widget>
      </item>
     </layout>
    </item>
    <item row='2' column='3'>
     <spacer name='horizontalSpacer_2'>
      <property name='orientation'>
       <enum>Qt::Horizontal</enum>
      </property>
      <property name='sizeHint' stdset='0'>
       <size>
        <width>42</width>
        <height>20</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row='3' column='2'>
     <spacer name='verticalSpacer_4'>
      <property name='orientation'>
       <enum>Qt::Vertical</enum>
      </property>
      <property name='sizeHint' stdset='0'>
       <size>
        <width>20</width>
        <height>27</height>
       </size>
      </property>
     </spacer>
    </item>
   </layout>
  </widget>
 </widget>
 <resources/>
 <connections/>
</ui>
";

    files.push(main_py);
    files.push(ui_mainwindow_py);
    files.push(mainwindow_ui);

    return files
}